#!/bin/bash
yum update -y
yum install -y httpd24 php56 git
service httpd start
chkconfig httpd on
groupadd www
usermod -a -G www ec2-user
chown -R root:www /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} +
find /var/www -type f -exec chmod 0664 {} +
cd /var/www/html
echo "<?php phpinfo(); ?>" > phpinfo.php
git clone https://github.com/4ndersonLin/aws-alb-test-page.git
cp /home/ec2-user/aws-alb-test-page/index-page/index.php /var/www/html/index.php